coverage:
  precision: 2
  round: down
  range: "45...100"
  status:
    project:
      default:
        target: 45%
        threshold: 6%
        base: auto 
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no
